insert into alignments (alignment, info) values ('Lawful Good (LG)', 'Lawful good creatures can be counted on to do the right thing as expected by society. Gold dragons, paladins, and most dwarves are lawful good.');
insert into alignments (alignment, info) values ('Neutral Good (NG)', 'Neutral folk do the best they can to help others according to their needs. Many celestials, some cloud giants, and most gnomes are neutral good.');
insert into alignments (alignment, info) values ('Chaotic Good (CG)', 'Chaotic good creatures act as their conscience directs, with little regard for what others expect. Copper dragons, many elves, and unicorns are chaotic good.');
insert into alignments (alignment, info) values ('Lawful Neutral (LN)', 'Lawful neutral individuals act in accordance with law, tradition, or personal codes. Many monks and some wizards are lawful neutral.');
insert into alignments (alignment, info) values ('Neutral (N)', 'Neutral is the alignment of those who prefer to steer clear of moral questions and dont take sides, doing what seems best at the time. Lizardfolk, most druids, and many humans are neutral.');
insert into alignments (alignment, info) values ('Chaotic Neutral (CN)', 'Chaotic neutral creatures follow their whims, holding their personal freedom above all else. Many barbarians and rogues, and some bards, are chaotic neutral.');
insert into alignments (alignment, info) values ('Lawful Evil (LE)', 'Lawful evil creatures methodically take what they want, within the limits of a code of tradition, loyalty, or order. Devils, blue dragons, and hobgoblins are lawful evil.');
insert into alignments (alignment, info) values ('Neutral Evil (NE)', 'Neutral evil is the alignment of those who do whatever they can get away with, without compassion or qualms. Many drow, some cloud giants, and goblins are neutral evil.');
insert into alignments (alignment, info) values ('Chaotic Evil (CE)', 'Chaotic evil creatures act with arbitrary violence, spurred by their greed, hatred, or bloodlust. Demons, red dragons, and orcs are chaotic evil.');
