insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Light Armor', 'Padded', '5 gp', '11 + Dex modifier', '—', 'Disadvantage', '8 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Light Armor', 'Leather', '10 gp', '11 + Dex modifier', '—', '—', '10 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Light Armor', 'Studded leather', '45 gp', '12 + Dex modifier', '—', '—', '13 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Medium Armor', 'Hide', '10 gp', '12 + Dex modifier (max 2)', '—', '—', '12 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Medium Armor', 'Chain Shirt', '50 gp', '13 + Dex modifier (max 2)', '—', '—', '20 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Medium Armor', 'Scale Mail', '50 gp', '14 + Dex modifier (max 2)', '—', 'Disadvantage', '45 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Medium Armor', 'Breastplate', '400 gp', '14 + Dex modifier (max 2)', '—', '—', '20 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Medium Armor', 'Half Plate', '750 gp', '15 + Dex modifier (max 2)', '—', 'Disadvantage', '40 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Heavy Armor', 'Ring Mail', '30 gp', '14', '—', 'Disadvantage;', '40 lb.');   
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Heavy Armor', 'Chain Mail', '75 gp', '16', 'Str 13', 'Disadvantage', '55 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Heavy Armor', 'Splint', '200 gp', '17', 'Str 15', 'Disadvantage', '60 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Heavy Armor', 'Plate', '1,500 gp', '18', 'Str 15', 'Disadvantage', '65 lb.');
insert into armor (category, name, cost, ac, strength, stealth, weight) values ('Shield', 'Shield', '10 gp', '+2', '—', '—', '6 lb.');
